version: '3.8'

services:
  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: .
      args:
        APP_DIR: /usr/app
    volumes:
      - $PUBLIC_FOLDER:/usr/app/public
    ports:
      - 3000:3000
    environment:
      JWT_ISSUER: $JWT_ISSUER
      MONGO_DB_URL: mongodb://mongo:27017/
      NODE_ENV: $NODE_ENV
      PUBLIC_URL: $PUBLIC_URL
  mongo:
    container_name: mongo
    image: mongo:5
    restart: unless-stopped
    volumes:
      - db:/data/db
    ports:
      - 27017:27017

volumes:
  db:

networks:
  default:
    name: news-aggregator
