version: '3.8'

services:
  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: .
      args:
        APP_DIR: /usr/app
    volumes:
      - $PUBLIC_FOLDER:/usr/app/public
    ports:
      - 3000:3000
    links:
      - mongo
    environment:
      JWT_ISSUER: $JWT_ISSUER
      NODE_ENV: $NODE_ENV
      PUBLIC_URL: $PUBLIC_URL
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017

networks:
  default:
    name: news-aggregator
